import pandas as pd
import numpy as np

print("----------------------------- import, export data --------------------------------")
data = pd.read_csv("student.csv")
print(data)
data.to_pickle("student.pickle")

print("----------------------------- concat --------------------------------")
df1 = pd.DataFrame(np.ones((3,4))*0, columns=['a','b','c','d'])
df2 = pd.DataFrame(np.ones((3,4))*1, columns=['a','b','c','d'])
df3 = pd.DataFrame(np.ones((3,4))*2, columns=['a','b','c','d'])
print(df1)
print(df2)
print(df3)
#print(df1.append(df2))
# axis=0 |, axis=1 ---- operation
res = pd.concat([df1,df2,df3], axis=0, ignore_index=True)
print(res)
print("----------------------------- join [inner, outer] --------------------------------")
df1 = pd.DataFrame(np.ones((3,4))*0, columns=['a','b','c','d'], index=[1,2,3])
df2 = pd.DataFrame(np.ones((3,4))*1, columns=['b','c','d','e'], index=[2,3,4])
print(df1)
print(df2)
print(pd.concat([df1, df2]))
print(pd.concat([df1, df2], join='outer'))
print(pd.concat([df1, df2], join='inner', ignore_index=True))
print("------------------------------")
print(df1)
print(df2)
print(pd.concat([df1,df2], axis=1))
#print(pd.concat([df1,df2], axis=1, join_axes=[df1.index]))