import numpy as np

print("--------------------------------- sort, argsort, partition, argpartition ------------------------------------")
#a = np.arange(13, 1, -1).reshape((3,4))
a = np.array([1, 8, 7, 5, 9, 3])
print(a)
print("--- sort  ---")
print(np.sort(a))
print("--------------------------------- arg means index ------------------------------------")
print("--- argsort ---")
print(np.argsort(a))

print("-------- partition ----------")
print(a)
print(np.partition(a, 2))
print(np.partition(a, 3))
print("------ put the second largest number at -2 (the tail 2) location ------")
print(a)
print(np.partition(a, -2))
print("------ find the largest 3 numbers  --------")
print(a)
print(np.partition(a, -3))
print("-------  [-3:] means -3 --> end   ---------")
print(np.partition(a, -3)[-3:])
print("------ find the smallest 3 numbers  --------")
print(np.partition(a, 3))
print("-------  [:3] means start --> 3   ---------")
print(np.partition(a, 3)[:3])

print("----------------------------- argpartition  -------------------------")
a=np.array([11, 5, 6, 8, 3, 4])
print(a)
print(np.partition(a, 3))
print(np.argpartition(a, 3))