import numpy as np
print("----------------------------------------------")
A = np.arange(3,15)
print(A)
print(A[3])
print()
A = np.arange(3,15).reshape((3,4))
print(A)
print("A[2]", A[2])
print("A[1,2]", A[1,2])
print("A[1][2]", A[1][2])
print("--------------- : or :: means all---------------")
print("A[2,:]", A[2,:])
print("A[:,1]", A[:,1])
print("A[::,1]", A[::,1])
print("A[1, 1:3]", A[1, 1:3])
print()
for r in A:
    print(r)
print()
print(A.T)
for c in A.T:
    print(c)

print()
print(A.flatten())
for item in A.flat:
    print(item)

print("------------------------array merge ---------------------------")
A = np.array([1,1,1])
B = np.array([2,2,2])
# vertical stack
print(np.vstack((A, B)))
C=np.vstack((A, B))
print(A.shape, C.shape)
# horizontal stack
D=np.hstack((A, B))
print(D)
print()
print(A)
print(A.T)
print()
print("A[np.newaxis,:]", A[np.newaxis,:])
print("A[np.newaxis,:].shape",A[np.newaxis,:].shape)
print("A[:,np.newaxis]")
print(A[:,np.newaxis])
print("A[:,np.newaxis].shape",A[:,np.newaxis].shape)
print("-------------")
print(A,B)
print(np.hstack((A, B)))
print(np.hstack((A[:,np.newaxis], B[:, np.newaxis])))
print("-------------")
C = np.concatenate((A, B), axis=0)
print(C)
#numpy.exceptions.AxisError: axis 1 is out of bounds for array of dimension 1
#print(np.concatenate((A,B), axis=1))
print("--------------------------")
D=np.array([1,1,1])[:, np.newaxis]
E=np.array([2,2,2])[:, np.newaxis]
print(D)
print(E)
print(np.concatenate((D, E), axis=1))
print("--------------------------------- split --------------------------------------")
A = np.arange(12).reshape((3,4))
print(A)
# 1 vertical split, 0 horizontal split
print(np.split(A, 2, axis=1))
print(np.split(A, 3, axis=0))
print()
print("np.array_split(A,3,axis=1)")
print(np.array_split(A,3,axis=1))
print("----------------------------------")
print(A)
print(np.vsplit(A, 3))
print(np.hsplit(A, 2))
print("------------------------------- copy ------------------------------")
a = np.arange(4)
print(a)
b = np.copy(a)
c = a.copy()
print(b)
a[1:3]=[22, 33]
print(a)
print(b)
print(c)
print(c[-1])